version: "3.7"

services:
  my-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/miniproject/index.js
      - ./email.js:/miniproject/email.js
      - ./phone.js:/miniproject/phone.js
      - ./cheerio.js:/miniproject/cheerio.js
      - ./swagger/users.swagger.js:/miniproject/swagger/users.swagger.js
      - ./swagger/tokens.swagger.js:/miniproject/swagger/tokens.swagger.js
      - ./swagger/starbucks.swagger.js:/miniproject/swagger/starbucks.swagger.js
    ports:
      - 3000:3000

  my-database:
    image: mongo:5
    ports:
      - 27017:27017
